### ISSUE TITLE
Nombre de las ramas

### ISSUE THREAD

**Issue by damiancastelao** [danielcastelao/mvc-SusanaSantosM#3]
Cambia el nombre de la rama "Susana", ya que esto da a entender que es una rama personal.
Utiliza nombres que se correspondan con el desarrollo, por ejemplo si esta rama es donde estás desarrollando el `observer` entonces mejor llamarla `observer`

**Comment by SusanaSantosM** [comment]
Listo! Cambie el nombre de la rama a observer
